site_name: RePlayOS Official Site
site_url: https://github.com/rtomasa/MkDocs_RePlay
site_author: Rubén Tomás
site_description: >-
  RePlayOS is a Linux distribution featuring a streamlined libretro frontend. It's specifically designed to emulate a wide range of classic game consoles, arcade machines, and computers. The OS focuses on delivering fast and user-friendly emulation experiences, optimized for use with Raspberry Pi boards. This emphasis on ease of use and broad compatibility makes it an ideal choice for enthusiasts looking to relive classic gaming moments on modern hardware.
copyright: >-
  Copyright &copy; <script>document.write(new Date().getFullYear())</script> <a href="https://github.com/rtomasa" target="_blank" rel="noopener">Rubén Tomás Alonso (RTA)</a> -
  <a href="#__consent">Change cookie settings</a>

repo_name: MkDocs_RePlay
repo_url: https://github.com/rtomasa/MkDocs_RePlay

theme:
  name: material
  logo: img/logo.png
  favicon: img/favicon.png
  font:
    text: Saira Semi Condensed
    code: Sometype Mono
  icon:
    repo: fontawesome/brands/github-alt
  language: en
  palette:
    scheme: slate
    primary: black
    accent: pink
  custom_dir: overrides
  features:
    - navigation.tracking
    - navigation.top
    - navigation.path
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy  

extra:
  analytics:
    provider: google
    property: G-78GVW6P3JY
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics:
        name: Google Analytics
        checked: true
      github:
        name: GitHub
        checked: true
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/rtomasal
    - icon: fontawesome/brands/discord
      link: https://discord.gg/2ghkKAWKDv
    - icon: fontawesome/brands/telegram
      link: https://t.me/replayos
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@RTA_RetroDev
    - icon: fontawesome/brands/github-alt
      link: https://github.com/rtomasa
    - icon: simple/patreon
      link: https://patreon.com/RePlayOS
  generator: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - tables

nav:
  - Home: index.md
  - Wiki (basic):
    - Requirements: sysreq.md
    - Supported Systems: systems.md
    - Installation & First Boot: install.md
    - Gamepad Configuration: gpadbasic.md
    - Keyboard Configuration: keyboard.md
    - Folder Structure: folders.md
    - Adding Games: addgames.md
    - Adding BIOS: addbios.md
    - Favorites & Recents: favrec.md
    - Video Configuration: videobasic.md
    - Input Lag: inputlag.md
    - Emulation Profiles: emuprofiles.md
    - Alpha Player: alphaplayer.md
  - Wiki (advanced):
    - EEPROM Update: eeprom.md
    - Wi-Fi Configuration: wifi.md
    - New Controllers Support: mappings.md
    - RePlay Custom Drivers & DIY: drivers.md
    - RePlay Options File: cfgfile.md 
    - Core System Settings: settings.md
    - Emulation Know-How: insights.md
    - ROM Codes and Meanings: romcodes.md
    - M3U Multi-Disc Management: m3u.md
    - Pi3/4 Audio Jack: pi3jack.md
    - ScummVM: scummvm.md
  - Common Issues: issues.md
  - Help & Support: support.md
  - F.A.Q: faq.md
  - Changelog: changelog.md
  - Download: download.md
  - About: about.md
  